run_id: "8_Genes_Analysis_Upgraded_Heatmaps_V2"

output_root: "/mnt/data/shahar/gwas_barley/morexV3_analysis/USED_Haplotype_Analysis/Wild_And_Elite/Target_Genes_analysis_Crosshap_Heatmap_Violin_Graphs"

merged_intersection_vcf_dir: "/mnt/data/shahar/gwas_barley/morexV3_analysis/USED_Haplotype_Analysis/Wild_And_Elite/Wild_And_Elite_VCFs__IntersectionMethod"
ld_vcf_root: "/mnt/data/shahar/gwas_barley/morexV3_analysis/USED_haplotype_vcfs_per_gene"
pheno_root: "/mnt/data/shahar/gwas_barley/morexV3_analysis/USED_Haplotype_Analysis/Wild_And_Elite/phenotype_files_wild&elite"

plink_bin: "plink"
minHap: 9
hetmiss_as: "allele"
keep_outliers: false

continue_on_error: true
overwrite_cache: false
fail_fast: false

stats:
  alpha: 0.05
  pairwise_method: "holm"
