#!/usr/bin/env Rscript
# =============================================================================
# 05_collect_significant_genes.R
#
# WHAT   Gather everything about the genes that passed BH into ONE browsable folder,
#        so the significant results can be reviewed without filtering tables or
#        hunting through the per-gene figure trees.
#
# READS  04_runs/<run_id>/Stats/gene_results.tsv   (+ haplotype_groups.tsv)
# WRITES 04_runs/<run_id>/Significant_genes/
#          significant_genes.tsv      one row per significant gene, ranked by q
#          haplotype_groups.tsv       per-group means for those genes only
#          CombinedPDF/NN__trait__gene__qX.pdf    crosshap tree + phenotype violin
#          Heatmaps/NN__trait__gene__qX.pdf       haplotype/genotype heatmaps
#          README.md
#
# Files are RANK-PREFIXED (01 = smallest q), so sorting by filename sorts by
# significance, and the same NN is the same gene in both folders. The trait is in
# every filename, so a per-trait view is just a sort or a glob.
#
# Figures are COPIED, not symlinked, so the folder can be moved or shared intact.
# Re-running rebuilds the folder from scratch.
# =============================================================================
Sys.setenv(TMPDIR = "/mnt/data/shahar/.tmp")
suppressPackageStartupMessages({ library(yaml); library(data.table) })

args <- commandArgs(trailingOnly = TRUE)
cfg_path <- if (length(args) >= 1) args[1] else
  "/mnt/data/shahar/gwas_barley/morexV3_analysis/barley_for_publication_project/04_USED_haplotype_analysis_crosshap/00_config/config.yaml"
cfg <- yaml::read_yaml(cfg_path)
run  <- file.path(cfg$output_root, "04_runs", cfg$run_id)
S    <- file.path(run, "Stats")
OUT  <- file.path(run, "Significant_genes")

gr <- fread(file.path(S, "gene_results.tsv"))
sig <- gr[significant_fdr == TRUE][order(fdr_q, kw_p_raw)]
if (!nrow(sig)) { cat("No significant genes; nothing to collect.\n"); quit(save="no") }

# Rebuild only what THIS script owns. `by_trait/` is produced later by
# 06_named_gene_figures.R (which needs the step-05 annotations), so wiping the whole
# folder here would silently destroy the named figures every time the stats are
# re-run. Clear the two subdirectories this script writes, and leave anything else.
for (sub in c("CombinedPDF", "Heatmaps")) unlink(file.path(OUT, sub), recursive = TRUE)
dir.create(file.path(OUT, "CombinedPDF"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(OUT, "Heatmaps"),    recursive = TRUE, showWarnings = FALSE)
if (dir.exists(file.path(OUT, "by_trait")))
  cat("note: by_trait/ left in place; re-run 06_named_gene_figures.R to refresh it\n")

sig[, rank := seq_len(.N)]
short <- sub("^HORVU\\.MOREX\\.r3\\.", "", sig$gene_id)
qtag  <- gsub("[^0-9a-zA-Z.+-]", "", formatC(sig$fdr_q, format = "g", digits = 2))
stem  <- sprintf("%02d__%s__%s__q%s", sig$rank, sig$trait, short, qtag)

copied <- 0L; missing <- character(0)
for (i in seq_len(nrow(sig))) {
  for (k in c("combined_pdf_path", "heatmap_pdf_path")) {
    src <- sig[[k]][i]
    dst <- file.path(OUT, if (k == "combined_pdf_path") "CombinedPDF" else "Heatmaps",
                     paste0(stem[i], ".pdf"))
    if (!is.na(src) && nzchar(src) && file.exists(src)) {
      file.copy(src, dst, overwrite = TRUE); copied <- copied + 1L
    } else missing <- c(missing, paste(sig$gene_id[i], k))
  }
}

## ---- the table, in reading order -------------------------------------------
out <- sig[, .(rank, trait, gene_id, gene_short = short, locus_id, class,
               chr, gene_start, gene_end, strand,
               lead_SNP, lead_neg_log10p, dist_to_lead_bp, n_snps_window,
               n_ind, n_unassigned, n_groups, group_sizes,
               kw_p_raw, fdr_q, eta_squared, delta_top_bottom_sd,
               top_group, top_n, top_mean, bottom_group, bottom_n, bottom_mean,
               description,
               figure_stem = stem)]
fwrite(out, file.path(OUT, "significant_genes.tsv"), sep = "\t", na = "NA")

hg_path <- file.path(S, "haplotype_groups.tsv")
if (file.exists(hg_path)) {
  hg <- fread(hg_path)
  fwrite(hg[gene_id %in% sig$gene_id & trait %in% sig$trait],
         file.path(OUT, "haplotype_groups.tsv"), sep = "\t", na = "NA")
}

## ---- README ------------------------------------------------------------------
con <- file(file.path(OUT, "README.md"), "w"); wl <- function(...) writeLines(paste0(...), con)
wl("# Significant genes — ", cfg$run_id)
wl("")
wl("Generated by `01_scripts/05_collect_significant_genes.R` on ",
   format(Sys.Date(), "%Y-%m-%d"), ". **Rebuilt from scratch on every run — do not edit by hand.**")
wl("")
wl("The ", nrow(sig), " genes with Benjamini-Hochberg **q <= ", cfg$stats$alpha,
   "** (within trait), out of ", nrow(gr), " tested. Everything else is in `../Stats/`.")
wl("")
wl("## How this folder is organised")
wl("")
wl("Files are **rank-prefixed**: `01` has the smallest q. Sorting by filename sorts by")
wl("significance, and the same number is the same gene in both folders.")
wl("")
wl("```")
wl("significant_genes.tsv   one row per gene, ranked — start here")
wl("haplotype_groups.tsv    per-haplotype-group n / mean / median / SD, these genes only")
wl("CombinedPDF/            crosshap tree + phenotype violin, one PDF per gene")
wl("Heatmaps/               haplotype and genotype heatmaps, one PDF per gene")
wl("```")
wl("")
wl("Filename pattern: `NN__trait__gene__qVALUE.pdf`, so `ls CombinedPDF/*fiber*`")
wl("gives that trait's figures in rank order.")
wl("")
wl("## The genes")
wl("")
wl("| # | trait | gene | locus | q | eta2 | top-vs-bottom | groups |")
wl("|---|---|---|---|---|---|---|---|")
for (i in seq_len(nrow(sig))) wl(sprintf("| %d | %s | %s | %s | %.2g | %.3f | %+.2f SD | %d |",
  sig$rank[i], sig$trait[i], short[i], sig$locus_id[i], sig$fdr_q[i],
  sig$eta_squared[i], sig$delta_top_bottom_sd[i], sig$n_groups[i]))
wl("")
wl("## Reading these numbers")
wl("")
wl("**`eta_squared`** = (H − k + 1)/(n − k): the share of phenotype rank variance explained")
wl("by haplotype group. **`delta_top_bottom_sd`** = highest-mean group minus lowest-mean")
wl("group, in phenotype SD. These matter more than q here: every gene in this list sits at")
wl("a locus that was *selected* for association with this trait, so a small p-value is close")
wl("to guaranteed — the effect size is what carries information.")
wl("")
nloc <- uniqueN(sig$locus_id)
wl("**Count loci, not just genes.** These ", nrow(sig), " genes sit in **", nloc, " loci**; genes")
wl("within a locus are in LD and are not independent discoveries. Per-locus counts are in")
wl("`../Stats/locus_summary.tsv`.")
wl("")
top <- sig[, .N, by = locus_id][order(-N)][1:min(3,.N)]
wl("Most gene-dense loci here: ",
   paste(sprintf("`%s` (%d genes)", top$locus_id, top$N), collapse = ", "), ".")
close(con)

cat(sprintf("Significant genes collected: %d (of %d tested), in %d loci\n",
            nrow(sig), nrow(gr), uniqueN(sig$locus_id)))
cat(sprintf("Figures copied: %d\n", copied))
if (length(missing)) { cat("MISSING figures:\n"); cat(paste0("  ", missing, collapse="\n"), "\n") }
cat(sprintf("Wrote %s\n", OUT))
